### ISSUE TITLE
Documenter la récupération des fichiers sources et le data management réalisé

### ISSUE THREAD

**Issue by ghost** [denisGustin/refpmsi#1]
Bonjour @denisGustin,

Merci pour votre package. Vous serait-il possible de documenter comment vous récupérez et faites le data management des bases proposées, via un document ou un script ?

Par exemple pour la CCAM PMSI : 
- quels fichiers téléchargez-vous ? 
- est-ce que la récupération est manuelle ou automatique ?
- quel traitement faites-vous pour obtenir le fichier .json ?

Merci encore

**Comment by denisGustin** [comment]
Bonjour

Les sources sont indiquées dans la colonne "Source" de la [liste des référentiels](https://denisgustin.github.io/refpmsi/articles/liste_ref.html) et détaillées peu à peu avec les liens dans des articles dédiés par référentiel. Exemple pour la [CIM-10 FR à usage PMSI](https://denisgustin.github.io/refpmsi/articles/cim.html#sources-3).

L'article détaillé pour la CCAM PMSI sera mis en ligne dans l'été.
Pour être tenu informé, s'inscrire à la [liste de diffusion du package.](http://www.lespmsi.com/r-et-pmsi/)

Pour le référentiel CCAM PMSI, la source = le fichier dit complémentaire à la liste analytique au format Excel diffusé par l'ATIH ([exemple V2 2021](https://www.atih.sante.fr/sites/default/files/public/content/3968/fichier_complementaire_ccam_descriptive_a_usage_pmsi_2021_v2.xlsx))

Le fichier est ensuite nettoyé manuellement (suppression colonnes non retenues) puis mis en tibble puis wranglé via un script dédié automatique (exemple : "ajustement sur 2 positions de l'extension" = dplyr::mutate(extension = stringr::str_pad(extension, width = 2, side = "left", pad = "0")), etc...)
La récupération est donc semi-automatique.

Mise en json zippé = 
json_object <- jsonlite::toJSON(ccam_pmsi, pretty=TRUE)
write(json_object, file=gzfile("ccam_pmsi.json.gz", encoding = "UTF-8"))
où ccam_pmsi est le tibble

**Comment by ghost** [comment]
OK merci beaucoup pour ces informations !

C'est bon de mon côté, donc je ferme ce ticket.

**Comment by Leto82** [comment]
Quel surprise de découvrir tout ce travail, la qualité et l'humilié qui faisait tellement défaut  aux médecin mercenaires qui ont eu raison de mon travail puis de ma passion. L'activité bouillonnante qui semble secouer le PMSI en ce moment me fascine et le travail que j'ai découvert avec ces équipes me sidère  totalement. Je vous remercie vous en particulier et je vous présente mes plus plates excuses pour ce que je vais faire de vos sources. C'est un trésor manipuler est triturer puis broyer en power point Copilot. Je suis incapable de mieux aider mes ex-collégues.
C'est fort de faire vivre l'information comme ça. C'es vitale.
